input ActorForCharacterRequest {
  old: [Int!]
  new: [PersonInput!]
}


input CharacterInput {
  _id: Int
  name: PersonNameInput
  age: Int
  birthDate: Date
  gender: PersonGender
  species: CharacterSpecies
  bio: String
  image: String
  actors: ActorForCharacterRequest
}

enum CharacterType {
  PRINCIPAL
  SECONDAIRE
}
