enum CharacterSpecies {
  ELFE
  DWARF
  HUMAN
  MONSTER
}

type Character {
  _id: Int
  name: PersonName
  age: Int
  birthDate: Date
  gender: PersonGender
  species: CharacterSpecies
  bio: String
  image: String
  actors: [Person]
  createdAt: Date
  editedAt: Date

  updates: [Update]
}
