input AnimeEpisodeInput {
  airing: Int
  nextAiringDate: Date
  total: Int
}

enum RelationMediaType {
  ANIME
  MANGA
}

enum RelationMediaLabel {
  PREQUEL
  SEQUEL
  SIDEQUEL
  SPIN_OFF
  SOURCE
  ADAPTATION
}

input AnimeRelationInput {
  type: RelationMediaType!
  label: RelationMediaLabel!
  _id: Int!
}

input AnimeInput {
  title: MediaTitleInput
  date: MediaDateInput
  image: MediaImageInput
  descrition: String
  source: AnimeSource
  format: AnimeFormat
  tags: [MediaTagInput]
  status: MediaStatus
  episodes: AnimeEpisodeInput
  explicitContent: Boolean
  links: [MediaLinkInput]
  studios: [CompanyInput]
  producers: [CompanyInput]
  relations: [AnimeRelationInput]
  staffs: [MediaRelStaffsInput]
  characters: [MediaRelCharactersInput]
  tracks: [MediaRelTracksInput]
}

type error {
  key: String,
  message: String
}

type outMessage {
  message: String
  errors: [error]
}

type Mutation {
  animeCreateRequest(reason: String, data: AnimeInput): outMessage
  animeUpdateRequest(reason: String, dataID: Int, changes: AnimeInput): outMessage
}
