input PersonNameInput {
  first: String
  end: String
  alias: [String]
}

input PersonInput {
  _id: Int
  label: PersonLabel
  name: PersonNameInput
  age: Int
  dateOfBirth: Date
  gender: PersonGender
  bio: String
  image: String
}
