input ArtistForTrackInput {
  old: [Int!]
  new: [PersonInput!]
}

input TrackInput {
  _id: Int
  label: TrackType
  name: String
  artists: ArtistForTrackInput
  episodes: [Int]
  createdDate: Date
}
