name: Node.js CI/CD

on:
  push:
    branches: [ production ]
  pull_request:
    branches: [ production ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [21.x, 22.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: pnpm install, build
      run: |
        pnpm install
        pnpm run build --if-present
