name: Node.js CI/CD

on:
  pull_request:
    branches: [production]

jobs:
  setup:
    runs-on: ActunimeProject-VM

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

  config_env:
    runs-on: ActunimeProject-VM
    needs: setup
    steps:
      - name: Configuration des variables de productions
        run: |
          touch .env.production
          echo MONGODB_URI=${{ secrets.MONGODB_URI }} >> .env.production
          echo MONGODB_user=${{ secrets.MONGODB_user }} >> .env.production
          echo MONGODB_pass=${{ secrets.MONGODB_pass }} >> .env.production
          echo MONGODB_dbName=${{ secrets.MONGODB_dbName }} >> .env.production

  docker_build:
    runs-on: ActunimeProject-VM
    needs: config_env
    steps:
      # - name: Arrêt du conteneur
      #   run: |
      #     docker stop actunime-api || true

      - name: Suppression de l'ancienne image test
        run: |
          docker image rm actunime-api-test-image || true

      - name: Construction de l'image docker test
        run: |
          docker build -f Dockerfile -t actunime-api-test-image .

      - name: Suppression de l'ancien conteneur test
        run: |
          docker rm actunime-api-test || true

      - name: Test Déploiement du conteneur test
        run: |
          docker run -d -p 3020:3020 --name actunime-api-test actunime-api-test-image

      - name: Arrêt du conteneur test
        run: |
          docker stop actunime-api-test || true
